//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBENTRADA
    {
        public int IDENTRADA { get; set; }
        public Nullable<int> IDDEPART { get; set; }
        public Nullable<int> IDOCUPACION { get; set; }
        public Nullable<int> IDMOTIVOENTRADA { get; set; }
        public string CEDULA { get; set; }
        public string NOMBRES { get; set; }
        public string APELLIDOS { get; set; }
        public Nullable<System.DateTime> FECHAENTRADA { get; set; }
        public string TiempoESTIMADO { get; set; }
        public string TENIACITA { get; set; }
    
        public virtual TBDEPARTAMENTO TBDEPARTAMENTO { get; set; }
        public virtual TBMOTIVOENTRADA TBMOTIVOENTRADA { get; set; }
        public virtual TBOCUPACION TBOCUPACION { get; set; }
    }
}
